### ISSUE TITLE
Automatic validation without of input type without attribute

### ISSUE THREAD

**Issue by lindeberg** [appany/AppAny.HotChocolate.FluentValidation#67]
When working with standard ASP.NET Web API-controllers with FluentValidation the validation happens of input types happens automatically without using an attribute on the input parameter

This would be cool to have in Hot Chocolate with this package.

**Comment by sergeyshaykhullin** [comment]
I designed this library to be explicit over implicit. It is better for large code bases, less error-prone and enable some useful optimizations with O(1) checks and zero allocations.

This library is not yet stable, everything might change, so if you have some thoughts - please share)

If you really want to use FluentValidation with the MVC experience you can check [FairyBread] (https://github.com/benmccallum/fairybread) project, it is getting better and better

**Comment by lindeberg** [comment]
Alright! Then I understand the this is not an issue but rather a focus of another package.

Would be interesting to read if you could write some lines somewhere about why explicit is better for large codebases (except for optimization).
