### ISSUE TITLE
Multiple mutations only first will return errors

### ISSUE THREAD

**Issue by falconmick** [appany/AppAny.HotChocolate.FluentValidation#93]
**Describe the bug**
If you run two seperate mutations like so:

```gql

mutation add($input: ThingInput) {
  add(input: $input) {
    id
  }
}

mutation addTwo($otherInput: ThingInput) {
  add(input: $otherInput) {
    id
  }
}

```

In this example only the validation from add will be returned.

If you started to return both mutations the Path would have to also infuse the name of the mutation I.e addTwo/add

**Comment by sergeyshaykhullin** [comment]
@falconmick Hello, thank you for a feature request!

If i understand you correct, you want to get operation name inside validation summary

I think it is good thing to implement https://github.com/appany/AppAny.HotChocolate.FluentValidation/pull/95

**Comment by falconmick** [comment]
That's partially it, I found that if I run 2 operations only the first shows up validation wise, so the other mutations validation results never get returned

**Comment by sergeyshaykhullin** [comment]
@falconmick I wrote a test case for multiple operations inside single mutation, i works fine https://github.com/appany/AppAny.HotChocolate.FluentValidation/pull/95/commits/304542e8afe36973059706291ebaa185156ef854

If you call same operation twice you should rename one/both

```gql
mutation add($input: ThingInput) {
  firstAdd: add(input: $input) {
    id
  }
  secondAdd: add(input: $input) {
    id
  }
}
```

**Comment by falconmick** [comment]
Ah yea that does work if you include the name of the field of the mutation (sorry I don't know terminology) but if you look at my example if your post request contains multiple standalone queries only the first returns. I could be wrong or maybe I'm misusing banana cake pop but it feels like it's not

**Comment by sergeyshaykhullin** [comment]
@falconmick You can run only single `mutation add($input: ThingInput) { ... }` at a time

If your document has multiple `query`/`mutation`/`subscription` statements, you should get a dropdown with all available operations
![image](https://user-images.githubusercontent.com/46970457/161304541-2fd190b5-0f4c-41ba-9a45-d4f848c8b044.png)

**Comment by sergeyshaykhullin** [comment]
Fixed in
- [x] https://github.com/appany/AppAny.HotChocolate.FluentValidation/pull/95
