### ISSUE TITLE
Is it possible to use a custom response model?

### ISSUE THREAD

**Issue by Toudahl** [appany/AppAny.HotChocolate.FluentValidation#99]
Hi,

I would like to introduce this package in the system that i am working on. Unfortunately it has been implemented with a custom response model.

I have been looking at the documentation for the [custom error mapping](https://github.com/appany/AppAny.HotChocolate.FluentValidation/blob/main/docs/examples/error-mappers.md#create-custom-error-mappers) unfortunately it seems that it cannot do what i need.

```
builder.Services
    .AddGraphQLServer()
    .AddFluentValidation(options =>
    {
        options.UseErrorMapper((errorBuilder, context) =>
        {
            var argument = (context.Argument as Argument)!;
            var objectField = (argument.DeclaringMember as ObjectField)!;
            if (Activator.CreateInstance(objectField.RuntimeType) is IResponseModel response)
            {
                response.ResponseResult = new ResponseResult
                {
                    GeneralValidationErrors =
                        context.ValidationResult.Errors.Select(error => error.ErrorMessage).ToList(),
                };
            }
        });
    })
    .AddMutationType<Mutation>()
    .AddQueryType<Query>();
```
In this example, i would like to return the `response` object instead of the normal structure.

I cannot seem to find a way to achieve that. Is it possible at all?

**Comment by sergeyshaykhullin** [comment]
GraphQL over http has two properties - `data` and `errors`

`{ "response": ... }` is a violation of this spec https://graphql.org/learn/serving-over-http/#response

ErrorMappers are responsible to fill `errors` object

**Comment by Toudahl** [comment]
Thank you for your reply.

I am aware that this goes against the spec. Unfortunately, the people that created this system initially didn't follow the spec.
The API is internal, so it won't give a nasty surprise to a consumer.

Unfortunately rewriting the error model we use is not a possibility.
But if I understand you correctly, you do not (and will not) support this? If so, feel free to close the issue.

Thanks for your time.

**Comment by sergeyshaykhullin** [comment]
This library is completely standing on HotChocolate execution pipeline, if it is possible to "rename" `data` with `response` (With custom graphql endpoint i guess) you need to grab your `QueryResult.Errors` inside custom endpoint and place it manually inside response like:

```json
{ "response": { "errors": {} } }
```

Or as preferable - add `errors` on top of response:

```json
{ "response": {}, "errors": {} }
```

Try to dig how your `/graphql` endpoint works and modify it to add `errors` same as `data`->`response` written

Hope i could help you ;)
